name: Pre-commit checks

on:
    pull_request:
        branches: ["*"]

jobs:
    pre-commit-checks:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Cache Node.js dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install dependencies
              run: yarn

            - name: Type check
              run: yarn check-types

            - name: Lint check
              run: yarn check-lint

            - name: Prettier check
              run: yarn check-format

            - name: Run tests
              run: yarn test
